### ISSUE TITLE
Perhaps use Curses

### ISSUE THREAD

**Issue by beoran** [apeiros/teaching_rpg#1]
Curses will give you much better input and output handling under the console and it is included by default in Ruby. The game now crashes if I press the wrong keys. With Curses that may be better.

http://www.ruby-doc.org/stdlib-1.9.3/libdoc/curses/rdoc/Curses.html

**Comment by apeiros** [comment]
Funky, it should not crash, at least it does not here. Curses proved troublesome in the past, and since we will switch to Gosu, once mechanics are deemed mature, I'll probably leave out Curses as a middlestep.

**Comment by beoran** [comment]
OK, I can agree with that. This issue needs to be closed anyway....
